### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by ryusuke-goto** [ryusuke-goto/praise_diary#88]
### サービス名
バズダイアリー(BUZZ DIARY)
### サービスURL
https://praise-diary.onrender.com

### ログインしていない状態で使える機能
- [ ] アプリ内で日記が一覧表示される機能(掲示板のように)
ホームメニューを選択すると、今までに作成された日記の一覧が表示される。
- [ ] 一覧の日記を選択すると、詳細画面が表示される機能
日記を選択すると、詳細な内容や添付した画像が表示される
- [ ] LINEログイン認証
ヘッダーのログインアイコンからLINEログインを実行できる。

### ログインした状態で使える機能
- [ ] ログアウト
ログアウトアイコンを選択するとログアウトできる。
- [ ] 日記作成機能
下部の+を選択すると、日記を作成できる。
- [ ] 日記の編集/削除機能
自分の作成した日記を削除、編集できる。
- [ ] 日記振り返り機能(カレンダー形式)
思い出メニューを選択すると、過去に作成した自分の日記を一覧で参照できる。
- [ ] 写真追加機能
日記作成時に、画像を添付できる。(1枚のみ)
- [ ] コメント作成機能
日記の詳細ページから、その日記に対してコメントを追加できる。
- [ ] プロフィール作成/編集機能
マイページメニューを選択すると、プロフィールが表示され、アバターの編集やステータスの編集が行える。
- [ ] 投稿された日、作成者などのフィルタ(検索)機能
検索メニューを選択すると、作成された全ての日記から、条件によって絞り込みができる。
- [ ] "いいね"が何回もできる機能
日記に表示されているハートボタンを押すと何回でもいいねを送ることができる。
- [ ] 今日の投稿全てに"いいね"できる機能
今日投稿された全ての日記に対していいねを送ることができる。連打可能。
- [ ] "いいね"を他の人にすればするほど、次の自分の投稿にもらえるいいねにバフがかかる(例："いいね"を5人の投稿にするごとに2倍)
チャレンジミッションとして、「10個の日記にいいねする」がある。
10個以上の日記にいいねを1つ以上することでミッションが達成され、自分の投稿に貰えるいいね数の増え方が変化する。(バフがかかる)
- [ ] 日記を毎日投稿するたびにバフがかかる。
デイリーミッションとして、「日記を投稿する。」がある。日記を投稿することでミッションが達成され、自分の投稿に貰えるいいね数の増え方が変化する。(バフがかかる)
- [ ] バフをもらうためのデイリーミッション表示機能(毎日達成できる難易度)
ミッションページを選択すると、デイリーかチャレンジを選ぶプルダウンが表示される。デイリーを選択するとミッション内容がモーダルで表示される。達成か未達成かの確認が可能
- [ ] バフをもらうためのチャレンジミッション機能(アプリを使い続ければ達成できる難易度)
ミッションページを選択すると、デイリーかチャレンジを選ぶプルダウンが表示される。チャレンジを選択するとミッション内容がモーダルで表示される。達成か未達成かの確認が可能
- [ ] デイリーミッションは、日付が変わるとユーザーごとに達成済のミッションをリセットされる。
デイリーミッションを達成した次の日にミッションページを確認すると、達成済だったものが未達成に戻っている。(バフは累積するためリセットされない)
- [ ] 毎日忘れないように、LINE通知を設定できる機能(例：22時から23時で設定すれば、アプリはその間の時間でユーザーのデバイスに日記を書いて！と通知する。)
LINEログインしたユーザーに対して、毎日の日記を忘れないよう通知する。アプリにすぐアクセスできるようリンクを表示する。

## READMEレビュー時から変更した機能
開発途中でMVPリリース時点で作らなくなった機能
- [ ] 投稿された日、作成者などのフィルタ(検索)機能
必須機能ではないため、MVP後に実装。
- [ ] プロフィール作成/編集機能
MVP後に実装。現在はログイン中のユーザー名を表示するのみ
- [ ] 毎日忘れないように、LINE通知を設定できる機能(例：22時から23時で設定すれば、アプリはその間の時間でユーザーのデバイスに日記を書いて！と通知する。)
MVP後に実装

## サービスイメージがわかるようなスクリーンショット等
特に管理画面など通常ユーザーが触れない機能があったら共有をお願いします

![Image](https://github.com/user-attachments/assets/596d2427-012b-4d5a-970c-973556bc4adf)

**Comment by kenchasonakai** [comment]
LGTMです！
